#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="${BUILD_DIR:-build}"
BUILD_TYPE="${BUILD_TYPE:-Debug}"
BUILD_TESTS="${BUILD_TESTS:-ON}"
BUILD_APPS="${BUILD_APPS:-ON}"
BUILD_EXAMPLES="${BUILD_EXAMPLES:-OFF}"
ENABLE_SANITIZERS="${ENABLE_SANITIZERS:-OFF}"
SANITIZERS="${SANITIZERS:-address,undefined}"

cmake -S . -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DKV_BUILD_TESTS="${BUILD_TESTS}" \
  -DKV_BUILD_APPS="${BUILD_APPS}" \
  -DKV_BUILD_EXAMPLES="${BUILD_EXAMPLES}" \
  -DKV_ENABLE_SANITIZERS="${ENABLE_SANITIZERS}" \
  -DKV_SANITIZERS="${SANITIZERS}"

cmake --build "${BUILD_DIR}" --parallel
