include(${CMAKE_CURRENT_LIST_DIR}/Warnings.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Sanitizers.cmake)

function(kv_setup_global_options)
    if(MSVC)
        add_compile_options(/utf-8)
    endif()
endfunction()

function(kv_add_executable_if_nonempty target source_file)
    if(EXISTS "${source_file}")
        file(SIZE "${source_file}" _size)
        if(_size GREATER 0)
            add_executable(${target} "${source_file}")
            target_link_libraries(${target} PRIVATE kv)
            target_compile_features(${target} PRIVATE cxx_std_17)
        else()
            message(STATUS "[skip] ${target}: ${source_file} is empty")
        endif()
    else()
        message(STATUS "[skip] ${target}: ${source_file} not found")
    endif()
endfunction()
